volumes:
  data:

services:
  bot:
    build:
      context: .
    environment:
      SIGNAL_USER_ACCOUNT: ${SIGNAL_USER_ACCOUNT}
      SIGNAL_GROUP_ID: ${SIGNAL_GROUP_ID}
      GOEIE_SETJES_SIGNAL_BOT_API_TOKEN: ${GOEIE_SETJES_SIGNAL_BOT_API_TOKEN}
      GOEIE_SETJES_PUBLIC_API: ${GOEIE_SETJES_PUBLIC_API}
    volumes:
      - data:/root/.local/share/signal-cli/data/
    init: true
